name: combined_barcode_scanner
description: Barcode scanner package that combines multiple sources behind a simple interface
version: 0.0.1
homepage: https://github.com/icapps/combined_barcode_scanner

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
