name: combined_barcode_scanner_unitech
description: A scanner plugin for integration with unitech mobile scanners
version: 0.0.1
homepage: https://github.com/icapps/combined_barcode_scanner
repository: https://github.com/icapps/combined_barcode_scanner

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  combined_barcode_scanner: ^0.0.1-dev.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.icapps.unitech_scanner
        pluginClass: UnitechScannerPlugin